name: Reproduction
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    container: 
      image: ghcr.io/zephyrproject-rtos/ci:v0.26.2
      options: --user root
    steps:    
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Build Zephyr Binaries
        run: |
          ls /opt/toolchains
          west init -l .
          ls $GITHUB_WORKSPACE/..
          west update -o=--depth=1 -n
          mkdir build_periph
          mkdir build_central
          ls /opt/toolchains/zephyr-sdk-${ZSDK_VERSION}/cmake
          export Zephyr-sdk_DIR=/opt/toolchains/zephyr-sdk-${ZSDK_VERSION}/cmake
          export PATH=$PATH:/opt/toolchains/zephyr-sdk-${ZSDK_VERSION}/cmake
          west build --board nrf52840dk/nrf52840 --build-dir build_periph $GITHUB_WORKSPACE/../zephyr/samples/bluetooth/peripheral_hr
          west build --board nrf52840dk/nrf52840 --build-dir build_central $GITHUB_WORKSPACE/../zephyr/samples/bluetooth/central_hr
          mv build_periph/zephyr/zephyr.elf $GITHUB_WORKSPACE/artifacts/periph.elf
          mv build_central/zephyr/zephyr.elf $GITHUB_WORKSPACE/artifacts/central.elf
      - name: Archive build results
        uses: actions/upload-artifact@v2
        with:
            name: zephyr-build
            path: |
                artifacts
  test:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        
      - name: Download zephyr binaries
        uses: actions/download-artifact@v2
        with:
          name: zephyr-build
                  
      - name: Run tests on latest Renode
        uses: antmicro/renode-test-action@v3.1.0
        with:
            renode-version: 'latest'
            tests-to-run: 'test.robot'
            renode-path: renode-latest
            artifacts-path: ${{ github.workspace }}


      - name: Archive latest results
        uses: actions/upload-artifact@v2
        if: always()
        with:
            name: test-results-latest
            path: |
                report.html
                log.html
                robot_output.xml


      - name: Run tests on Renode stable release
        uses: antmicro/renode-test-action@v3.1.0
        if: always()
        with:
            renode-version: '1.15.0'
            tests-to-run: 'test.robot'
            artifacts-path: ${{ github.workspace }}


      - name: Archive Renode release results
        uses: actions/upload-artifact@v2
        if: always()
        with:
            name: test-results-stable
            path: |
                report.html
                log.html
                robot_output.xml

