name: Reproduction
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    container: 
      image: ghcr.io/zephyrproject-rtos/ci:v0.26.12
      options: --user root
    steps:    
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Build Zephyr Binaries
        run: |
          cd /tmp/
          west init
          west update -o=--depth=1 -n
          mkdir build_periph
          mkdir build_central
          west build --board nrf52840dk_nrf52840 --build-dir build_periph $GITHUB_WORKSPACE/../zephyr/samples/bluetooth/peripheral_hr
          west build --board nrf52840dk_nrf52840 --build-dir build_central $GITHUB_WORKSPACE/../zephyr/samples/bluetooth/central_hr
          
          # move build files to artifacts dir
          mv build_periph/zephyr/zephyr.elf $GITHUB_WORKSPACE/artifacts/periph.elf
          mv build_central/zephyr/zephyr.elf $GITHUB_WORKSPACE/artifacts/central.elf


      - name: Archive build results
        uses: actions/upload-artifact@v2
        with:
            name: zephyr-build
            path: |
                artifacts
  test:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        
      - name: Download zephyr binaries
        uses: actions/download-artifact@v2
        with:
          name: zephyr-build
          
      - name: Verify binaries path
        run: sudo apt-get install tree -y && tree
                  
      - name: Run tests on latest Renode
        uses: antmicro/renode-test-action@v2.0.0
        with:
            renode-version: 'latest'
            tests-to-run: 'test.robot'
            renode-path: renode-latest
            artifacts-path: ${{ github.workspace }}


      - name: Archive latest results
        uses: actions/upload-artifact@v2
        if: always()
        with:
            name: test-results-latest
            path: |
                report.html
                log.html
                robot_output.xml


      - name: Run tests on Renode stable release
        uses: antmicro/renode-test-action@v2.0.0
        if: always()
        with:
            renode-version: '1.13.3'
            tests-to-run: 'test.robot'
            renode-path: renode-1.13
            artifacts-path: ${{ github.workspace }}


      - name: Archive Renode release results
        uses: actions/upload-artifact@v2
        if: always()
        with:
            name: test-results-stable
            path: |
                report.html
                log.html
                robot_output.xml

