name: Reproduction
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    container: 
      image: nordicplayground/nrfconnect-sdk:v2.4-branch
      options: --user root
    steps:    
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Build Zephyr Binaries
        run: ./build.sh

      - name: Archive build results
        uses: actions/upload-artifact@v2
        with:
            name: build-results
            path: |
                artifacts
  test:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-results
        
      - name: Run tests on latest Renode
        uses: antmicro/renode-test-action@v2.0.0
        with:
            renode-version: 'latest'
            tests-to-run: 'test.robot'
            renode-path: renode-latest


      - name: Archive latest results
        uses: actions/upload-artifact@v2
        if: always()
        with:
            name: test-results-latest
            path: |
                report.html
                log.html
                robot_output.xml


      - name: Run tests on Renode stable release
        uses: antmicro/renode-test-action@v2.0.0
        if: always()
        with:
            renode-version: '1.13.3'
            tests-to-run: 'test.robot'
            renode-path: renode-1.13


      - name: Archive Renode release results
        uses: actions/upload-artifact@v2
        if: always()
        with:
            name: test-results-stable
            path: |
                report.html
                log.html
                robot_output.xml

